name: DeepSource Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate coverage report
        run: npm test -- --coverage

      - name: Install DeepSource CLI
        run: curl https://deepsource.io/cli | sh

      - name: Report coverage to DeepSource
        run: ./bin/deepsource report --analyzer=test-coverage --key=javascript --value-file=./coverage/coverage.xml
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
